name: Security Scanner

on:
  # push:
  #   branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  codeql:
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Autobuild
        run: dotnet build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
